const mockApartments = [
  {
    id: 1,
    street: "123 Street",
    unit: "1B",
    city: "Buffalo",
    state: "NY",
    square_footage: 1000,
    price: "1500",
    bedrooms: 2,
    bathrooms: 1.5,
    pets: "yes!",
    image:
      "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img/https://www.glenwoodnyc.com/wp-content/uploads/2022/05/2-JSP-LOBBY-01-02-1280.jpg",
    user_id: 1,
  },
  {
    id: 2,
    street: "32 Boulevard",
    unit: "4 and a half",
    city: "San Diego",
    state: "CA",
    square_footage: 500,
    price: "30,000,000",
    bedrooms: 0,
    bathrooms: 0.5,
    pets: "NO",
    image: "https://www.moriliving.com/images/home/img_slide_003.jpg",
    user_id: 1,
  },
  {
    id: 3,
    street: "85 Yellow Snow RD",
    unit: "5P",
    city: "New York",
    state: "NY",
    square_footage: 800,
    price: "999,999,999,999,999",
    bedrooms: 1,
    bathrooms: 0,
    pets: "NO",
    image: "https://www.moriliving.com/images/home/img_slide_006.jpg",
    user_id: 1,
  },
];

export default mockApartments;
